// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDcE9Fm5j050OW25jHHtyempPud8BJ6XKo',
    appId: '1:804543974480:web:ea0962e60011c6503b1555',
    messagingSenderId: '804543974480',
    projectId: 'fir-example-eb616',
    authDomain: 'fir-example-eb616.firebaseapp.com',
    storageBucket: 'fir-example-eb616.firebasestorage.app',
    measurementId: 'G-PZZMKENZ8K',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBuHml6eV8ETWqZI1YUt12tiF2BVtrm_DY',
    appId: '1:804543974480:android:12a03e840a4165213b1555',
    messagingSenderId: '804543974480',
    projectId: 'fir-example-eb616',
    storageBucket: 'fir-example-eb616.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDi1_lJUkopuvLSKZ0TaaYk4ZcrdCFo3pA',
    appId: '1:804543974480:ios:e711996b1fcf2f573b1555',
    messagingSenderId: '804543974480',
    projectId: 'fir-example-eb616',
    storageBucket: 'fir-example-eb616.firebasestorage.app',
    iosBundleId: 'com.example.firebaseexample',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDi1_lJUkopuvLSKZ0TaaYk4ZcrdCFo3pA',
    appId: '1:804543974480:ios:e711996b1fcf2f573b1555',
    messagingSenderId: '804543974480',
    projectId: 'fir-example-eb616',
    storageBucket: 'fir-example-eb616.firebasestorage.app',
    iosBundleId: 'com.example.firebaseexample',
  );

}